sudo: required
services:
    - docker

before_install:
    - docker build -t manbobo2002/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run manbobo2002/react-test npm test -- --coverage

after_success:
    - docker build -t manbobo2002/multi-client ./client
    - docker build -t manbobo2002/multi-nginx ./nginx
    - docker build -t manbobo2002/multi-server ./server
    - docker build -t manbobo2002/multi-worker ./worker
    #Login to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub 
    - docker push manbobo2002/multi-client
    - docker push manbobo2002/multi-nginx
    - docker push manbobo2002/multi-server
    - docker push manbobo2002/multi-worker
